import React, { useState } from "react";

const WalletAndWithdrawl = ({ darkMode }) => {
  const [withdrawAmount, setWithdrawAmount] = useState("");
  const [withdrawals, setWithdrawals] = useState([
    { id: "WDR-001", amount: 500, date: "2024-07-20", status: "Approved", reason: "Processed successfully" },
    { id: "WDR-002", amount: 120, date: "2024-07-18", status: "Pending", reason: "Awaiting admin approval" },
    { id: "WDR-003", amount: 75.5, date: "2024-07-15", status: "Rejected", reason: "Bank details mismatch" },
    { id: "WDR-004", amount: 300, date: "2024-07-12", status: "Approved", reason: "Processed successfully" },
    { id: "WDR-005", amount: 80, date: "2024-07-10", status: "Pending", reason: "Awaiting admin approval" },
  ]);

  const generateReceipt = (withdrawal) => {
    const canvas = document.createElement('canvas');
    canvas.width = 800;
    canvas.height = 1000;
    const ctx = canvas.getContext('2d');

    // Background
    ctx.fillStyle = '#ffffff';
    ctx.fillRect(0, 0, canvas.width, canvas.height);

    // Header
    ctx.fillStyle = '#2563eb';
    ctx.fillRect(0, 0, canvas.width, 120);

    // Company Name
    ctx.fillStyle = '#ffffff';
    ctx.font = 'bold 36px Arial';
    ctx.textAlign = 'center';
    ctx.fillText('WITHDRAWAL RECEIPT', canvas.width / 2, 70);

    // Receipt ID
    ctx.fillStyle = '#1e293b';
    ctx.font = 'bold 24px Arial';
    ctx.textAlign = 'left';
    ctx.fillText(`Receipt ID: ${withdrawal.id}`, 60, 180);

    // Date
    ctx.font = '18px Arial';
    ctx.fillStyle = '#64748b';
    ctx.fillText(`Date: ${withdrawal.date}`, 60, 220);

    // Divider
    ctx.strokeStyle = '#e2e8f0';
    ctx.lineWidth = 2;
    ctx.beginPath();
    ctx.moveTo(60, 260);
    ctx.lineTo(740, 260);
    ctx.stroke();

    // Details Section
    ctx.fillStyle = '#1e293b';
    ctx.font = 'bold 20px Arial';
    ctx.fillText('WITHDRAWAL DETAILS', 60, 310);

    ctx.font = '18px Arial';
    ctx.fillStyle = '#475569';
    
    ctx.fillText('Amount:', 60, 360);
    ctx.font = 'bold 24px Arial';
    ctx.fillStyle = '#2563eb';
    ctx.fillText(`$${withdrawal.amount.toFixed(2)} USD`, 60, 395);

    ctx.font = '18px Arial';
    ctx.fillStyle = '#475569';
    ctx.fillText('Status:', 60, 450);
    
    // Status badge
    const statusColor = withdrawal.status === 'Approved' ? '#22c55e' : 
                       withdrawal.status === 'Pending' ? '#eab308' : '#ef4444';
    ctx.fillStyle = statusColor;
    ctx.fillRect(60, 465, 150, 35);
    ctx.fillStyle = '#ffffff';
    ctx.font = 'bold 16px Arial';
    ctx.textAlign = 'center';
    ctx.fillText(withdrawal.status, 135, 488);
    ctx.textAlign = 'left';

    ctx.font = '18px Arial';
    ctx.fillStyle = '#475569';
    ctx.fillText('Reason:', 60, 545);
    ctx.fillStyle = '#1e293b';
    ctx.fillText(withdrawal.reason, 60, 575);

    // Divider
    ctx.strokeStyle = '#e2e8f0';
    ctx.beginPath();
    ctx.moveTo(60, 630);
    ctx.lineTo(740, 630);
    ctx.stroke();

    // Footer
    ctx.fillStyle = '#64748b';
    ctx.font = '16px Arial';
    ctx.textAlign = 'center';
    ctx.fillText('This is an automated receipt generated by the system.', canvas.width / 2, 700);
    ctx.fillText('For any queries, please contact support.', canvas.width / 2, 730);
    
    ctx.fillStyle = '#94a3b8';
    ctx.font = '14px Arial';
    ctx.fillText('Thank you for using our service!', canvas.width / 2, 800);

    // Border
    ctx.strokeStyle = '#cbd5e1';
    ctx.lineWidth = 3;
    ctx.strokeRect(0, 0, canvas.width, canvas.height);

    return canvas.toDataURL('image/png');
  };

  const downloadReceipt = (withdrawal) => {
    const dataUrl = generateReceipt(withdrawal);
    const link = document.createElement('a');
    link.download = `withdrawal-receipt-${withdrawal.id}.png`;
    link.href = dataUrl;
    link.click();
  };

  const handleWithdraw = () => {
    if (!withdrawAmount || isNaN(withdrawAmount))
      return alert("Enter a valid amount!");
    const newRequest = {
      id: `WDR-00${withdrawals.length + 1}`,
      amount: parseFloat(withdrawAmount),
      date: new Date().toISOString().split("T")[0],
      status: "Pending",
      reason: "Awaiting admin approval",
    };
    setWithdrawals([newRequest, ...withdrawals]);
    setWithdrawAmount("");
    
    // Auto-download receipt
    setTimeout(() => downloadReceipt(newRequest), 100);
    
    alert("Withdrawal request submitted! Receipt downloaded.");
  };

  return (
    <div
      className={`min-h-screen px-4 sm:px-6 md:px-10 transition-all duration-300 ${
        darkMode ? "bg-gray-900 text-white" : "bg-gray-50 text-gray-900"
      }`}
      style={{ paddingTop: "2.5rem", paddingBottom: "4rem" }}
    >
      <div className="max-w-6xl mx-auto space-y-8">
        {/* Balance Card */}
        <div
          className={`border rounded-2xl p-6 sm:p-8 shadow-sm text-center sm:text-left ${
            darkMode ? "bg-gray-800 border-gray-700" : "bg-white border-gray-200"
          }`}
        >
          <p className="text-sm text-gray-500 mb-1">Current Available Balance</p>
          <h2 className="text-4xl font-semibold mb-1">$1,250.75</h2>
          <p className="text-xs text-gray-400">Last updated: July 22, 2024</p>
        </div>

        {/* Withdrawal Section */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {/* Left - Initiate Withdrawal */}
          <div
            className={`border rounded-2xl p-6 sm:p-8 shadow-sm ${
              darkMode ? "bg-gray-800 border-gray-700" : "bg-white border-gray-200"
            }`}
          >
            <h3 className="text-lg font-semibold mb-4">Initiate Withdrawal</h3>
            <label className="block text-sm mb-2 text-gray-500">
              Amount to Withdraw (USD)
            </label>
            <input
              type="text"
              value={withdrawAmount}
              onChange={(e) => setWithdrawAmount(e.target.value)}
              placeholder="e.g., 500.00"
              className={`w-full p-3 border rounded-md mb-4 text-sm outline-none ${
                darkMode
                  ? "bg-gray-900 border-gray-700 text-white placeholder-gray-400"
                  : "bg-white border-gray-300 text-gray-900 placeholder-gray-500"
              }`}
            />
            <button
              onClick={handleWithdraw}
              className="w-full py-3 bg-blue-600 text-white rounded-md hover:bg-blue-700 font-medium transition"
            >
              REQUEST WITHDRAWAL
            </button>
          </div>

          {/* Right - Important Note */}
          <div
            className={`border rounded-2xl p-6 sm:p-8 shadow-sm ${
              darkMode ? "bg-gray-800 border-gray-700" : "bg-white border-gray-200"
            }`}
          >
            <h3 className="text-lg font-semibold mb-4">Important Note</h3>
            <p className="text-sm text-gray-500 leading-relaxed">
              All withdrawal requests are subject to admin review and approval,
              and will be processed within 24–48 hours. <br />
              <br />
              Please ensure your bank details are updated in your profile
              settings to avoid delays.
            </p>
          </div>
        </div>

        {/* Withdrawal History Table */}
        <div
          className={`border rounded-2xl p-6 sm:p-8 shadow-sm ${
            darkMode ? "bg-gray-800 border-gray-700" : "bg-white border-gray-200"
          }`}
        >
          <h3 className="text-lg font-semibold mb-4">Withdrawal History</h3>

          <div className="overflow-x-auto">
            <table className="min-w-full text-sm border-collapse">
              <thead>
                <tr
                  className={`text-left ${
                    darkMode ? "bg-gray-700 text-gray-200" : "bg-gray-100 text-gray-700"
                  }`}
                >
                  <th className="py-3 px-4 font-semibold whitespace-nowrap">Request ID</th>
                  <th className="py-3 px-4 font-semibold whitespace-nowrap">Amount (USD)</th>
                  <th className="py-3 px-4 font-semibold whitespace-nowrap">Date</th>
                  <th className="py-3 px-4 font-semibold whitespace-nowrap">Status</th>
                  <th className="py-3 px-4 font-semibold whitespace-nowrap">Reason</th>
                  <th className="py-3 px-4 font-semibold whitespace-nowrap">Receipt</th>
                </tr>
              </thead>
              <tbody>
                {withdrawals.map((w) => (
                  <tr
                    key={w.id}
                    className={`border-t hover:bg-gray-50 transition ${
                      darkMode
                        ? "border-gray-700 hover:bg-gray-700/40"
                        : "border-gray-200"
                    }`}
                  >
                    <td className="py-3 px-4">{w.id}</td>
                    <td className="py-3 px-4">${w.amount.toFixed(2)}</td>
                    <td className="py-3 px-4">{w.date}</td>
                    <td className="py-3 px-4">
                      <span
                        className={`px-2 py-1 rounded-full text-xs font-medium ${
                          w.status === "Approved"
                            ? "bg-green-100 text-green-700"
                            : w.status === "Pending"
                            ? "bg-yellow-100 text-yellow-700"
                            : "bg-red-100 text-red-700"
                        }`}
                      >
                        {w.status}
                      </span>
                    </td>
                    <td className="py-3 px-4">
                      {w.status === "Rejected" ? (
                        <span className="text-red-500">{w.reason}</span>
                      ) : (
                        <span className="text-gray-500">{w.reason}</span>
                      )}
                    </td>
                    <td className="py-3 px-4">
                      <button
                        onClick={() => downloadReceipt(w)}
                        className="px-3 py-1 bg-blue-600 text-white rounded hover:bg-blue-700 text-xs font-medium transition"
                      >
                        Download
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
};

export default WalletAndWithdrawl;